spring:
  application:
    name: MSEurika

server:
  port: 4040

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:4040/eureka
