server:
  port: 5000

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: Capteurs
          uri: lb://CAPTEURS-SERVICE  # nom exact du service dans Eureka
          predicates:
            - Path=/capteurs/**  
          filters:
            - RewritePath=/capteurs/(?<segment>.*), /${segment}
        - id: Irrigation
          uri: lb://IRRIGATION-SERVICE
          predicates:
            - Path=/irrigation/**  
          filters:
            - RewritePath=/irrigation/(?<segment>.*), /${segment}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4040/eureka

management:
  endpoints:
    web:
      exposure:
        include:  health,info,gateway,refresh
   endpoint:
    gateway:
      enabled: true
      access: read-only
