server:
  port: 5000

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: CAPTEURS-SERVICE
          uri: lb://CAPTEURS-SERVICE
          predicates:
            - Path=/capteurs/**
          filters:
            - RewritePath=/capteurs/(?<segment>.*), /api/${segment}

        - id: IRRIGATION-SERVICE
          uri: lb://IRRIGATION-SERVICE
          predicates:
            - Path=/irrigation/**
          filters:
            - RewritePath=/irrigation/(?<segment>.*), /api/${segment}

# =========================
# EUREKA
# =========================
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # Changé localhost -> discovery-service
      defaultZone: http://discovery-service:4040/eureka

# =========================
# MANAGEMENT
# =========================
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: read-only
