server:
  port: 5000

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: Capteurs
          uri: lb://CAPTEURS-SERVICE
          predicates:
            - Path=/capteurs/**
          filters:
            - name: RewritePath
              args:
                regexp: /capteurs/(?<segment>.*)
                replacement: /api/capteurs/${segment}
                
        - id: Mesures
          uri: lb://CAPTEURS-SERVICE
          predicates:
            - Path=/mesures/**
          filters:
            - name: RewritePath
              args:
                regexp: /mesures/(?<segment>.*)
                replacement: /api/mesures/${segment}

        - id: Parcelles
          uri: lb://IRRIGATION-SERVICE
          predicates:
            - Path=/parcelles/**
          filters:
            - name: RewritePath
              args:
                regexp: /parcelles/(?<segment>.*)
                replacement: /api/parcelles/${segment}

        - id: Actions
          uri: lb://IRRIGATION-SERVICE
          predicates:
            - Path=/actions/**
          filters:
            - name: RewritePath
              args:
                regexp: /actions/(?<segment>.*)
                replacement: /api/actions/${segment}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4040/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: read-only
