server:
  port: 5000

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: Capteurs
          uri: lb://CAPTEURS-SERVICE
          predicates:
            - Path=/capteurs/**
          filters:
            - name: RewritePath
              args:
                regexp: /capteurs/(?<segment>.*)
                replacement: /${segment}

        - id: Irrigation
          uri: lb://IRRIGATION-SERVICE
          predicates:
            - Path=/irrigation/**
          filters:
            - name: RewritePath
              args:
                regexp: /irrigation/(?<segment>.*)
                replacement: /${segment}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4040/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
