spring:
  application:
    name: Getway
  config:
    import: "configserver:http://localhost:9999"

server:
  port: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: MSProjet
          uri: lb://MSProjet
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects/(?<lien>.*), /${lien}

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: read-only
