server:
  port: 8082

spring:
  application:
    name: irrigation-service

  datasource:
    url: jdbc:mysql://localhost:3306/irrigation?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: irrigation-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted-packages: "*"

  # Configuration du Config Server
  config:
    import: optional:configserver:http://localhost:9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4040/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
