server:
  port: 8082

spring:
  application:
    name: irrigation-service

  config:
    # Changé localhost -> config-service
    import: optional:configserver:http://config-service:9999

  datasource:
    # Changé localhost -> db-mysql et password -> root
    url: jdbc:mysql://db-mysql:3306/irrigation?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    # Changé localhost -> kafka
    bootstrap-servers: kafka:9092
    consumer:
      group-id: irrigation-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Changé localhost -> discovery-service
      defaultZone: http://discovery-service:4040/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
